apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-provisioner
  namespace: cephfs
  labels:
    app: cephfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cephfs-provisioner
  template:
    metadata:
      labels:
        app: cephfs-provisioner
    spec:
      containers:
        - name: cephfs-provisioner
          image: "registry.cn-shanghai.aliyuncs.com/jieee/cephfs-provisioner:latest"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          env:
            - name: PROVISIONER_NAME
              value: ceph.com/cephfs
            - name: PROVISIONER_SECRET_NAMESPACE
              value: cephfs
          command:
            - "/usr/local/bin/cephfs-provisioner"
          args:
            - "-id=cephfs-provisioner-1"
      serviceAccount: cephfs-provisioner