apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs  # sc名称需要保持一致