kind: Deployment
apiVersion: apps/v1
metadata:
  name: alicloud-nas-controller
  namespace: nas
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alicloud-nas-controller
  template:
    metadata:
      labels:
        app: alicloud-nas-controller
    spec:
      tolerations:
        - operator: "Exists"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: nfs-provisioner
      hostNetwork: true
      containers:
        - name: nfs-provisioner
          image: egistry.cn-shanghai.aliyuncs.com/jieee/alicloud-nas-controller:v1.14.3.8
          env:
            - name: PROVISIONER_NAME
              value: alicloud/nas
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: nas
      volumes:
        - hostPath:
            path: /data
          name: nas