kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc2
  annotations:
    volume.beta.kubernetes.io/storage-class: ali-nas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi