apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rdb
  namespace: ceph
provisioner: kubernetes.io/rbd  # 这里要和controller中的PROVISIONER_NAME保持一致
parameters:
  monitors: 10.0.30.11:6789,10.0.30.12:6789,10.0.30.13:6789  # ceph monitor 地址
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: ceph
  pool: kube
  userId: admin
  userSecretName: ceph-secret
  userSecretNamespace: ceph