apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbd-provisioner
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbd-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
        - name: rbd-provisioner
          image: registry.cn-shanghai.aliyuncs.com/jieee/rbd-provisioner:latest
          env:
            - name: PROVISIONER_NAME
              value: ceph.com/rbd