kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc1
  annotations:
    volume.beta.kubernetes.io/storage-class: ceph-rdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi